added new app using ratatui
tui-rs-revival/ratatui pull request #113
Opened 2023-03-23 01:55 UTC by BrookJeynes

2023-03-23 04:11 UTC, sayanarijit approved these changes

2023-03-23 08:42 UTC, orhun requested changes

2023-03-23 08:42 UTC, orhun commented on APPS.md
> +| [oxycards](https://github.com/BrookJeynes/oxycards)                        | Oxycards is a quiz card application built within the terminal                                                          |
Formatting looks a bit off. Can you align this row with the other table rows?

2023-03-27 02:39 UTC, sayanarijit approved these changes

2023-03-27 08:43 UTC, orhun approved these changes

2023-03-27 08:43 UTC, merged