fix: FromStr in Color Struct
tui-rs-revival/ratatui pull request #180
Opened 2023-05-18 21:25 UTC by Mehrbod2002

fixes: #143

2023-05-19 09:34 UTC, joshka requested changes
There's a note in the issue about whether we should / shouldn't bring in a new dependency for this (it seems like a fairly small amount of code to avoid doing so). I could go either way, but lean towards not bringing it in. Do we gain anything by putting the implementation off onto colorsys?

2023-05-19 10:08 UTC, Mehrbod2002 commented on src/style.rs
> +                    Self::Rgb(rgb.red() as u8, rgb.green() as u8, rgb.blue() as u8)
but I should think without #

2023-05-19 13:46 UTC, sophacles requested changes
Code looks good to me.

Would like to see documentation - its non-obvious how to make Indexed and Rgb from a string without reading the code.

2023-05-19 18:08 UTC, orhun commented
I think we should also add unit tests for this.

2023-05-19 18:38 UTC, Mehrbod2002 commented
> I think we should also add unit tests for this.

The tests added

2023-05-19 23:00 UTC, joshka approved these changes
Nice work. This looks good to me.

2023-05-20 14:36 UTC, sophacles submitted a review, later dismissed

2023-05-20 15:07 UTC, sophacles requested changes
There's some edge cases that we probably want to deal with.

2023-05-20 15:07 UTC, sophacles commented on src/style.rs
> +    }
Modifying this test to: 
```rust
    #[test]
    fn test_invalid_colors() {
        let bad_colors = [
            "invalid_color", // not a color string
            "abcdef0",       // 7 chars is not a color
            " bcdefa",       // doesn't start with a '#'
            "blue ",         // has space at end
            " blue",         // has space at start
            "#abcdef00",     // too many chars
        ];

        for bad_color in bad_colors {
            assert!(
                Color::from_str(bad_color).is_err(),
                "bad color: '{}'",
                bad_color
            );
        }
    }
```
Fails

2023-05-20 15:07 UTC, sophacles commented on src/style.rs
> +                } else if let (Ok(r), Ok(g), Ok(b)) = (
If we do something like this (my code here is ugly, but gets the job done):
```rust
                } else if let (Ok(r), Ok(g), Ok(b)) = {
                    if !s.starts_with('#') || s.len() != 7 {
                        return Err(ParseColorError);
                    }
                    (
                        u8::from_str_radix(&s[1..3], 16),
                        u8::from_str_radix(&s[3..5], 16),
                        u8::from_str_radix(&s[5..7], 16),
                    )
                } {
                    Self::Rgb(r, g, b)
```
The test cases below pass.

2023-05-20 16:29 UTC, sophacles approved these changes

2023-05-20 16:42 UTC, orhun approved these changes
Neat.

2023-05-20 16:43 UTC, merged