feat(style): Add style with fn
tui-rs-revival/ratatui pull request #287
Opened 2023-07-01 12:26 UTC by a-kenji

This allows the full style to be constructed in a const context.

A const style can be used in the following way:

```
const DEFAULT_MODIFIER: Modifier = Modifier::BOLD.union(Modifier::ITALIC);
const EMPTY: Modifier = Modifier::empty();
const DEFAULT_STYLE: Style = Style::with(DEFAULT_MODIFIER, EMPTY)
.fg(Color::Red).bg(Color::Black);
```

2023-07-01 15:39 UTC, orhun approved these changes

2023-07-01 22:17 UTC, joshka requested changes
I prefer not to have methods that have two parameters of the same type because anyone reading the code unfamiliar with the library will always have to look up what each parameter indicates.

However, this can done without a new method by making `add/remove_modifier()` const. The implementations only have to change slightly to support this as `insert()` / `remove()` on `bitflags` aren't const-safe:

```rust
    pub const fn add_modifier(mut self, modifier: Modifier) -> Style {
        self.sub_modifier = self.sub_modifier.difference(modifier);
        self.add_modifier = self.add_modifier.union(modifier);
        self
    }

    pub const fn remove_modifier(mut self, modifier: Modifier) -> Style {
        self.add_modifier = self.add_modifier.difference(modifier);
        self.sub_modifier = self.sub_modifier.union(modifier);
        self
    }

    #[test]
    fn style_can_be_const() {
        const _RED: Color = Color::Red;
        const _BLACK: Color = Color::Black;
        const _BOLD: Modifier = Modifier::BOLD;
        const _ITALIC: Modifier = Modifier::ITALIC;

        const _RESET: Style = Style::reset();
        const _RED_FG: Style = Style::new().fg(_RED);
        const _BLACK_BG: Style = Style::new().bg(_BLACK);
        const _ADD_BOLD: Style = Style::new().add_modifier(_BOLD);
        const _REMOVE_ITALIC: Style = Style::new().remove_modifier(_ITALIC);
        const _ALL: Style = Style::new()
            .fg(_RED)
            .bg(_BLACK)
            .add_modifier(_BOLD)
            .remove_modifier(_ITALIC);
        assert_eq!(
            _ALL,
            Style::new()
                .fg(Color::Red)
                .bg(Color::Black)
                .add_modifier(Modifier::BOLD)
                .remove_modifier(Modifier::ITALIC)
        );
```

2023-07-01 22:20 UTC, joshka commented
Also - please try to give a name to the commit that indicates the user facing benefit (e.g. "make Style support const context" or something similar).

2023-07-02 09:29 UTC, a-kenji commented
Thank you for the review, this is indeed a much better solution!

2023-07-08 10:12 UTC, joshka approved these changes

2023-07-08 10:13 UTC, merged

2023-07-08 10:13 UTC, joshka commented
Rebased and approved. Thanks for this :)