docs(canvas): add documentation for x_bounds, y_bounds
tui-rs-revival/ratatui pull request #35
Opened 2023-02-12 22:05 UTC by orhun

> Upstream: [#666](https://github.com/fdehau/tui-rs/pull/666)

## Description

There is no description in docs for `Canvas::x_bounds` and `Canvas::y_bounds`, but there is a [question](https://github.com/fdehau/tui-rs/issues/286) about that with response of the author. So this PR puts this response as documentation for the methods with some small corrections and formatting.

## Testing guidelines

This PR does not add any code, but all code fragments in documentation are valid & buildable.

## Checklist

* [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
* [x] I have added relevant tests.
* [x] I have documented all new additions.

2023-02-16 22:17 UTC, mindoodoo commented on src/widgets/canvas/mod.rs
> +    ///
Since both additions are pretty much the same, maybe we could avoid some wordiness by linking to the ```x_bounds``` ?

2023-02-28 12:41 UTC, mindoodoo requested changes
I feel like we don't really need the examples in the end. If the issue is ever brought up again we can add them back in, but for the time being we could simplify this

2023-02-28 12:41 UTC, mindoodoo commented on src/widgets/canvas/mod.rs
> +    /// bounds.
Maybe not really needed ? A bit wordy

2023-02-28 12:41 UTC, mindoodoo commented on src/widgets/canvas/mod.rs
> +    /// bounds.
Maybe not really need ? A bit wordy.

2023-03-03 03:20 UTC, sayanarijit reviewed
@mindoodoo @orhun Feel free to merge the suggested changes if you agree with it.

2023-03-03 03:20 UTC, sayanarijit commented on src/widgets/canvas/mod.rs
> +    /// bounds.
```suggestion
    /// Define the viewport of the canvas.
    /// If you were to "zoom" to a certain part of the world you may want to choose different
    /// bounds.
```

2023-03-03 03:20 UTC, sayanarijit commented on src/widgets/canvas/mod.rs
> +    /// If you were to "zoom" to a certain part of the world you may want to choose different
```suggestion
    /// Define the viewport of the canvas.
    ///
    /// If you were to "zoom" to a certain part of the world you may want to choose different
```

2023-03-19 16:30 UTC, merged