docs: add some lines of documentation to clear doubts
tui-rs-revival/ratatui pull request #38
Opened 2023-02-12 22:06 UTC by orhun

> Upstream: [#677](https://github.com/fdehau/tui-rs/pull/677)

## Description
It is a PR just to resolve issue #352

Add a few lines to explain how to define the coordinates 

## Testing guidelines
Just test it using VS Code

## Checklist

* [X] I have read the [contributing guidelines](../CONTRIBUTING.md).
* [X] I have added relevant tests.
* [X] I have documented all new additions.

2023-02-15 21:07 UTC, Nickiel12 approved these changes
Although it feels a little bit wordy, it will be a lot clearer for those not familiar with the ui design.

2023-02-16 21:28 UTC, mindoodoo commented
The way this PR defines X and Y is very unclear imo.

Also, looking at the original issue, it would seem like the main difference between OPs perception of the x and y coordinate system and the actual tui implementation is only that the origin is in the top left instead of bottom left.

2023-02-18 16:47 UTC, Nickiel12 commented
Maybe just a note somewhere prominent that "The origin is in the upper left corner for all widgets"?

2023-02-21 10:36 UTC, mindoodoo commented
I honestly feel like it's pretty common sense that the origin is in the top left corner in tui applications. It also feels weird to specify it in this small case where as I'm sure there's dozens if not hundreds of places we could specify this in this crate.

2023-02-21 10:59 UTC, sayanarijit requested changes
Added personal opinions.

2023-02-21 10:59 UTC, sayanarijit commented on src/layout.rs
> +    /// The Rect is always drawn from the top left to the bottom and to the right of the container.
I don't think these docs are needed since the fields are/will be already documented.

2023-02-21 10:59 UTC, sayanarijit commented on src/widgets/canvas/line.rs
> +///
These should be above the respective fields.

2023-02-21 10:59 UTC, sayanarijit commented on src/widgets/canvas/line.rs
> +/// And when it is drawn, it will calculate the distance between the two points
These docs aren't necessary, since there's nothing unexpected here.

2023-02-22 12:41 UTC, mindoodoo commented
If I can get a couple upvotes on this message, I'll close this PR I think. We can take another look at it if someone requests it again.

2023-02-25 13:38 UTC, mindoodoo commented
Alright, closing this then, if someone stumbles on this and disagrees / would like to discuss it further, feel free to open a discussion.

2023-02-25 13:38 UTC, closed without merging