better safe shared layout cache
tui-rs-revival/ratatui pull request #62
Opened 2023-02-18 20:27 UTC by conradludgate

## Description

https://github.com/tui-rs-revival/tui-rs-revival/pull/22#issuecomment-1427143924 introduced the idea to return `&'static [Rect]` on `Layout::split` using unsafe, but we can use a safe abstraction here instead with `Rc`.

## Testing guidelines

Using the benchmark introduced in #22, I get these results (master/this respectively)

```
test layout::tests::bench_vertical_split_by_height ... bench: 129 ns/iter (+/- 6)
test layout::tests::bench_vertical_split_by_height ... bench: 100 ns/iter (+/- 3)
```

## Checklist

* [X] I have read the [contributing guidelines](../CONTRIBUTING.md).
* [X] I have added relevant tests.
* [ ] I have documented all new additions.

2023-02-19 02:36 UTC, sayanarijit approved these changes

2023-02-20 07:25 UTC, sayanarijit requested changes
Need to fix test failure.

2023-02-20 13:33 UTC, sayanarijit approved these changes

2023-02-20 14:48 UTC, adamkali approved these changes
I think these changes are also better in the long run, using explicit `Rc<[Rect]>` could end up being more maintainable in other parts of the code. We should look into other parts of the codebase where using a safe pointer instead of a vector, to if there will be benefits there.

2023-03-11 17:53 UTC, orhun approved these changes

2023-03-12 12:41 UTC, mindoodoo approved these changes

2023-03-12 12:53 UTC, merged

2023-03-24 03:42 UTC, StratusFearMe21 commented
Hey! This is pretty cool 😄👍! I'm glad someone was able to put my work to use.